name = "linkedin-sim"
compatibility_date = "2026-04-02"
compatibility_flags = ["nodejs_compat"]
pages_build_output_dir = ".vercel/output/static"

[[d1_databases]]
binding = "DB"
database_name = "linkedin-sim-db"
database_id = "666365db-786d-4a31-a492-61b49b6c08db"
